import 'imports-loader?jQuery=jquery!redactorLib'
import 'imports-loader?jQuery=jquery!redactorSource'
import '../libs/redactor/redactor.css'
import 'core-js/es7/reflect'
import 'zone.js/dist/zone'
import 'ts-helpers'
import './wallhaven-450488.png'
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic'
import { AppModule } from './app.module'
platformBrowserDynamic().bootstrapModule(AppModule)
